export const GET_ORDERINFORMATION = "GET_ORDERiNFORMATION";
export const UPDATE_DELIVERYTYPE = "UPDATE_DELIVERYTYPE";
export const ADD_PIZZA = "ADD_PIZZA";
export const REMOVE_PIZZA = "REMOVE_PIZZA";
export const UPDATE_PIZZA = "UPDATE_PIZZA";
export const PROCESS_ORDER = "PROCESS_ORDER";


